# -*- coding: utf-8 -*-
"""Heart Disease(latest latest).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlasT_pDm8tLGzLOyL0bpa47U8mGSXNx

# Heart Disease Prediction — SVM
This notebook walks through the pipeline in the order I actually worked through it: look at the data first, decide what's wrong with it, fix each thing for a documented reason, then model. Every "why" is written next to the step it belongs to, not collected somewhere else.

## 1. Setup
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                              roc_auc_score, roc_curve, confusion_matrix,
                              ConfusionMatrixDisplay, classification_report,RocCurveDisplay)
from sklearn.inspection import permutation_importance
import joblib


sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (7, 5)

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

def section(title):
    width = 70
    print("\n" + "=" * width)
    print(title.center(width))
    print("=" * width)

"""## 2. First look at the data
Before touching anything, just look: shape, types, and whether the target is balanced. This decides which metrics matter later.
"""

df = pd.read_csv("heart_disease.csv")
df.head()

print(df.shape)

df.info()

df.describe().T

df.isnull().sum()

# Strip whitespace from string columns
str_cols = df.select_dtypes(include='object').columns.tolist()
for c in str_cols:
    df[c] = df[c].astype(str).str.strip().replace('nan', pd.NA)

# Check and remove duplicate rows
df = df.duplicated().sum()



target_col = "Heart Disease Status"
print(df[target_col].value_counts())
sns.countplot(x=target_col, data=df)
plt.title("Class distribution: Heart Disease Status")
plt.show()

"""**Observation:** 8,000 "No" vs 2,000 "Yes" — an 80/20 split. A model that just predicts "No" every time scores 80% accuracy while catching zero real cases. So from this point on: stratify every split on the target, and judge models on precision/recall/F1/AUC, never accuracy alone."""

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = [c for c in df.columns if c not in numeric_cols and c != target_col]

# ==========================
# Distribution of all numeric variables
# ==========================
fig, axes = plt.subplots(3, 3, figsize=(16, 12))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):

    sns.histplot(
        df[col],
        bins=30,
        kde=True,
        color="steelblue",
        edgecolor="black",
        ax=axes[i]
    )

    axes[i].set_title(col,
                      fontsize=11,
                      fontweight="bold")

    axes[i].set_xlabel("")
    axes[i].grid(axis="y", alpha=0.3)

plt.suptitle("Distribution of Numerical Variables",
             fontsize=16,
             fontweight="bold")

plt.tight_layout()
plt.show()

# ==========================
# QQ-plots: numeric variables vs theoretical uniform distribution
# ==========================
import scipy.stats as stats

fig, axes = plt.subplots(3, 3, figsize=(16, 12))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    data = df[col].dropna()
    a, b = data.min(), data.max()
    stats.probplot(data, dist=stats.uniform(loc=a, scale=b - a), plot=axes[i])
    axes[i].set_title(col, fontsize=11, fontweight="bold")
    axes[i].get_lines()[0].set_markerfacecolor("steelblue")
    axes[i].get_lines()[0].set_markersize(3)

plt.suptitle("QQ-Plots: Observed Quantiles vs. Theoretical Uniform Distribution", fontsize=14)
plt.tight_layout()
plt.show()

sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(4, 3, figsize=(16, 14))
axes = axes.flatten()

for i, col in enumerate(categorical_cols):
    # Calculate percentage dataframe cleanly
    df_pct = (
        df[col]
        .value_counts(normalize=True)
        .mul(100)
        .reset_index()
    )
    df_pct.columns = [col, "Percentage"]

    # Horizontal bar plot
    sns.barplot(
        data=df_pct,
        x="Percentage",
        hue=col,
        legend=False,
        y=col,
        ax=axes[i],
        palette="Blues_r"
    )

    axes[i].set_title(col, fontsize=11, fontweight="bold")
    axes[i].set_xlabel("Percentage (%)", fontsize=9)
    axes[i].set_ylabel("")
    axes[i].set_xlim(0, 70)  # Leaves room on the right for text labels

    # Add precise percentage labels on each bar
    for p in axes[i].patches:
        width = p.get_width()
        axes[i].annotate(
            f"{width:.1f}%",
            (width + 1.5, p.get_y() + p.get_height() / 2.0),
            ha="left",
            va="center",
            fontsize=9
        )

# Hide unused subplots
for j in range(len(categorical_cols), len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Categorical Variable Distributions (%)", fontsize=16, fontweight="bold")
plt.tight_layout()
plt.show()

# ==========================
# Correlation heatmap of numeric predictors
# ==========================
plt.figure(figsize=(10, 8))
corr = df[numeric_cols].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            square=True, linewidths=0.5, cbar_kws={"shrink": 0.8})
plt.title("Correlation Heatmap of Numerical Attributes")
plt.tight_layout()
plt.show()

# # ==========================
# # Heart Disease Distribution by Age Group
# # ==========================
# heart_disease_counts = df[df['Heart Disease Status'] == "Yes"]

# age = df[
#     (df['Heart Disease Status'] == "Yes") &
#     (df['Age'] >= 20) &
#     (df['Age'] <= 25)
# ]

# # Count patients by age
# age_counts = age['Age'].value_counts().sort_index()

# plt.figure(figsize=(12, 6))
# plt.bar(age_counts.index, age_counts.values, color='steelblue')

# plt.xlabel('Age of patients that have heart disease')
# plt.ylabel('Total number of patients')
# plt.title('Bar Chart of Heart Disease Status')
# plt.show()

# # ==========================
# # Diabetes Distribution
# # ==========================

# # Heart disease patients only
# df_yes = df[df['Heart Disease Status'] == "Yes"]

# # Age range 20–30
# age = df_yes[(df_yes['Age'] >= 20) & (df_yes['Age'] <= 30)]
# #
# plt.figure(figsize=(10, 5))

# sns.countplot(data=age, x="Age", hue="Diabetes", palette="Set2")

# plt.title("Diabetes Status by Age (Patients around 20–30)")
# plt.xlabel("Age")
# plt.ylabel("Number of Patients")

# plt.show()

# # ==========================
# # Stress Level Distribution
# # ==========================

# df = df[df['Heart Disease Status'] == "Yes"]

# label_map = {0: "Low", 1: "Medium", 2: "High"}

# stress_level_counts = df['Stress Level'].map(label_map).value_counts()

# plt.figure(figsize=(8, 8))
# plt.pie(stress_level_counts, labels=stress_level_counts.index, autopct='%1.1f%%', startangle=90, colors=['lightgreen', 'gold', 'lightsalmon'])
# plt.title('Stress Level Distribution Among Heart Disease Patients')
# plt.axis('equal')
# plt.show()

"""## 3. Data quality checks

> Add blockquote


Standard checklist before deciding on any cleaning: duplicates, invalid values, inconsistent category labels, and missing data.
"""

print("Duplicate rows:", df.duplicated().sum())

print("Numeric columns:", numeric_cols)
print("Categorical columns:", categorical_cols)

# Category labels: check nothing like "yes"/"Yes "/"YES" slipped in
for c in categorical_cols:
    print(c, df[c].dropna().unique())

"""No duplicates, and every categorical column has exactly the labels it should (no case mismatches, no stray whitespace variants). Nothing to clean up there."""

missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_summary = pd.DataFrame({"missing_count": missing, "missing_%": missing_pct})

df_missing = missing_summary[missing_summary["missing_count"] > 0].sort_values("missing_%", ascending=False).reset_index()
df_missing.rename(columns={'index': 'Variable'}, inplace=True)

# 2. Plotting the chart
fig, ax = plt.subplots(figsize=(8, 8))

# Define colors (highlighting the top one in red, rest in blue)
colors = ['#c44e52' if i == 0 else '#4c72b0' for i in range(len(df_missing))]

# Create the horizontal bar chart
bars = ax.barh(df_missing['Variable'], df_missing['missing_%'], color=colors, height=0.6)

# Invert Y-axis to have the highest value at the top
ax.invert_yaxis()

# Add labels and titles
ax.set_xlabel('Missing (%)')
ax.set_title('Percentage of Missing Values by Variable', fontweight='bold', pad=20)

# Dynamically set the X-axis limit based on your highest missing percentage (plus some padding)
max_missing = df_missing['missing_%'].max()
ax.set_xlim(0, max_missing + 5)

# Add percentage text annotations next to each bar
for bar in bars:
    width = bar.get_width()
    ax.text(
        width + (max_missing * 0.02), # Dynamic X position padding
        bar.get_y() + bar.get_height() / 2,
        f'{width:.2f}%',
        va='center',
        fontsize=8
    )

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

"""Every column except the target has *some* missingness, but there are clearly two different situations here:
- 19 columns sit at roughly 0.2–0.3% missing — small enough that it's almost certainly just noise
- **Alcohol Consumption** is missing on 25.86% of rows — far too much to treat the same way

That gap is big enough that it deserves an actual test, not an assumption, before deciding what to do with it.

## 4. Is Alcohol Consumption's missingness random?
The concern with a variable missing on a quarter of the data: if *why it's missing* is connected to the outcome we're predicting, filling it in with the mode would quietly erase real signal. If it's unrelated to everything, imputing is safe.

So: build an indicator for "was Alcohol Consumption missing on this row", and test whether that indicator relates to every other variable — including, specifically, the target. This is the test the group's earlier draft ran in bulk across every column, but the one comparison that actually matters for this decision (missingness vs. the target) got buried among 20 others. Isolating it here.
"""

alcohol_col = "Alcohol Consumption"
is_missing = df[alcohol_col].isnull()

mcar_rows = []

# numeric predictors: does the average differ between rows where alcohol is missing vs not?
for col in numeric_cols:
    valid = df[col].notnull()
    stat, p = stats.ttest_ind(df.loc[valid & is_missing, col],
                               df.loc[valid & ~is_missing, col],
                               equal_var=False)
    mcar_rows.append({"variable": col, "test": "t-test", "statistic": round(stat, 3), "p_value": round(p, 4)})

# categorical predictors + the target itself
for col in [c for c in categorical_cols if c != alcohol_col] + [target_col]:
    valid = df[col].notnull()
    ct = pd.crosstab(is_missing[valid], df.loc[valid, col])
    chi2, p, dof, exp = stats.chi2_contingency(ct)
    mcar_rows.append({"variable": col, "test": "chi-square", "statistic": round(chi2, 3), "p_value": round(p, 4)})

mcar_df = pd.DataFrame(mcar_rows).sort_values("p_value").reset_index(drop=True)
n_tests = len(mcar_df)
bonf_threshold = 0.05 / n_tests
mcar_df

n_sig_raw = (mcar_df["p_value"] < 0.05).sum()
n_sig_bonf = (mcar_df["p_value"] < bonf_threshold).sum()
print(f"Tests run: {n_tests}")
print(f"Significant at raw p<0.05: {n_sig_raw}")
print(f"Bonferroni-corrected threshold: {bonf_threshold:.5f}  ->  significant: {n_sig_bonf}")

mcar_plot_df = mcar_df.copy()

# Convert p-value to -log10(p-value)
mcar_plot_df["neg_log10_p"] = -np.log10(mcar_plot_df["p_value"])

# Identify target comparison
mcar_plot_df["is_target"] = mcar_plot_df["variable"] == target_col

# Sort by p-value (largest to smallest)
mcar_plot_df = mcar_plot_df.sort_values("p_value", ascending=False).reset_index(drop=True)

# Bonferroni correction threshold
bonf_threshold_mcar = 0.05 / len(mcar_plot_df)

# Colours
colors = mcar_plot_df["is_target"].map({
    True: "crimson",
    False: "steelblue"
})

plt.figure(figsize=(8, 8))

# Lollipop lines
plt.hlines(
    y=mcar_plot_df["variable"],
    xmin=0,
    xmax=mcar_plot_df["neg_log10_p"],
    color="lightgrey",
    linewidth=1
)

# Points
plt.scatter(
    mcar_plot_df["neg_log10_p"],
    mcar_plot_df["variable"],
    color=colors,
    s=70,
    zorder=3
)

# Significance thresholds
plt.axvline(
    -np.log10(0.05),
    color="orange",
    linestyle="--",
    linewidth=1,
    label="Raw significance threshold (p = 0.05)"
)

plt.axvline(
    -np.log10(bonf_threshold_mcar),
    color="crimson",
    linestyle="--",
    linewidth=1,
    label="Bonferroni corrected threshold"
)

# Labels
plt.xlabel(
    "-log10(p-value) from missingness association tests\n"
    "(further right = stronger evidence against MCAR)"
)

plt.ylabel("Variable")

plt.title(
    "MCAR Test: Association Between Alcohol Consumption Missingness\n"
    "and Observed Variables"
)

plt.legend(
    fontsize=8,
    loc="lower right"
)

plt.tight_layout()
plt.show()

"""**Result: nothing comes close to significant** — not even at the uncorrected 0.05 level, let alone after Bonferroni correction, and that includes the comparison against the target (p ≈ 0.26). Whether a patient's alcohol consumption was recorded looks unrelated to every other variable in the dataset, including whether they have heart disease.

That's the signature of data **Missing Completely At Random (MCAR)** (Little & Rubin, 2019) — not MAR (which would show up as a significant association with *other* predictors) and not MNAR (which would show up as an association with the target/outcome itself).

**Decision:** because it's MCAR, standard imputation (e.g. mode) would technically be "safe" in the sense of not biasing the model. But at 25.86% missing, mode-filling would still artificially flatten a quarter of this feature's variance for no benefit. Since there's no informative pattern to preserve *or* destroy, the simplest and most transparent option is to keep the missing rows as their own explicit category rather than guessing a value for them.

## 6. Outliers
Check each numeric column against the standard 1.5×IQR rule before deciding whether capping is even needed.
"""

plt.figure(figsize=(10, 8))

sns.boxplot(
    data=df[numeric_cols],
    orient="h"
)

plt.title("Boxplot of Numerical Features")
plt.xlabel("Value")
plt.ylabel("Features")

plt.tight_layout()
plt.show()

outlier_counts = {}
for col in numeric_cols:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lb, ub = q1 - 1.5*iqr, q3 + 1.5*iqr
    outlier_counts[col] = ((df[col] < lb) | (df[col] > ub)).sum()

pd.Series(outlier_counts, name="n_outliers").to_frame()

"""Zero outliers by the IQR rule on every numeric column — every value already sits inside its documented realistic range (e.g. Age 18–80, BMI 18–40). No capping needed; capping something that isn't there would just be an unnecessary transformation.

### 7. Does anything actually relate to the target?
Worth checking *before* modelling, not just after — if nothing here correlates with the outcome, that sets the right expectation for what the models can realistically achieve.
"""

y_temp = df[target_col].map({"No": 0, "Yes": 1})

pb_rows = []
for col in numeric_cols:
    valid = df[col].notnull() & y_temp.notnull()
    r, p = stats.pointbiserialr(y_temp[valid], df.loc[valid, col])
    pb_rows.append({"variable": col, "point_biserial_r": round(r, 4), "p_value": round(p, 4)})
table_numeric = pd.DataFrame(pb_rows).sort_values("p_value").reset_index(drop=True)
table_numeric

chi_rows = []
for col in categorical_cols:
    ct = pd.crosstab(df[col], df[target_col])
    chi2, p, dof, exp = stats.chi2_contingency(ct)
    n_obs = ct.sum().sum()
    cramers_v = np.sqrt(chi2 / (n_obs * (min(ct.shape) - 1)))
    chi_rows.append({"variable": col, "chi2": round(chi2, 3), "p_value": round(p, 4), "cramers_v": round(cramers_v, 4)})
table_categorical = pd.DataFrame(chi_rows).sort_values("p_value").reset_index(drop=True)
table_categorical

# Prepare numeric effect sizes
numeric_effect = table_numeric[["variable", "point_biserial_r", "p_value"]].copy()
numeric_effect["effect_size"] = numeric_effect["point_biserial_r"].abs()
numeric_effect = numeric_effect[["variable", "effect_size", "p_value"]]

# Prepare categorical effect sizes
categorical_effect = table_categorical[["variable", "cramers_v", "p_value"]].copy()
categorical_effect = categorical_effect.rename(columns={"cramers_v": "effect_size"})

# Combine both tables
effect_df = pd.concat([numeric_effect, categorical_effect], ignore_index=True)

# Bonferroni correction
bonf_threshold = 0.05 / len(effect_df)

effect_df["significance"] = "Not significant"
effect_df.loc[effect_df["p_value"] < 0.05, "significance"] = "Raw p < 0.05"
effect_df.loc[effect_df["p_value"] < bonf_threshold, "significance"] = "Bonferroni significant"

# Sort by effect size
effect_df = effect_df.sort_values("effect_size", ascending=False)

# Plot effect sizes
palette = {
    "Not significant": "lightgrey",
    "Raw p < 0.05": "orange",
    "Bonferroni significant": "crimson"
}

plt.figure(figsize=(7, 8))

sns.barplot(
    data=effect_df,
    x="effect_size",
    y="variable",
    hue="significance",
    palette=palette,
    dodge=False
)

plt.axvline(
    x=0.1,
    color="black",
    linestyle="--",
    label="Small effect (0.1)"
)

plt.xlabel("Effect Size")
plt.ylabel("")
plt.title("Association Strength Between Predictors and Target")
plt.legend()
plt.tight_layout()
plt.show()

# ==========================
# Numeric predictors by Heart Disease Status
# ==========================
fig, axes = plt.subplots(3, 3, figsize=(16, 12))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    sns.boxplot(data=df, x=target_col, y=col, hue=target_col,
                palette=["#4c72b0", "#c44e52"], legend=False, ax=axes[i])
    axes[i].set_title(col, fontsize=11, fontweight="bold")
    axes[i].set_xlabel("")

plt.suptitle("Numerical Attributes by Heart Disease Status", fontsize=14)
plt.tight_layout()
plt.show()

# ==========================
# Categorical predictors: % Heart Disease = Yes per category
# ==========================
fig, axes = plt.subplots(4, 3, figsize=(16, 14))
axes = axes.flatten()

for i, col in enumerate(categorical_cols):
    prop = (
        df.groupby(col)[target_col]
        .apply(lambda x: (x == "Yes").mean() * 100)
        .reset_index(name="pct_yes")
    )
    sns.barplot(data=prop, x=col, y="pct_yes", hue=col, legend=False,
                palette="Blues_d", ax=axes[i])
    axes[i].axhline(20, color="grey", linestyle="--", linewidth=1)
    axes[i].set_title(col, fontsize=11, fontweight="bold")
    axes[i].set_ylabel("% Heart Disease = Yes")
    axes[i].set_xlabel("")

for j in range(len(categorical_cols), len(axes)):
    axes[j].axis("off")

plt.suptitle("Heart Disease Rate by Category (dashed line = overall 20% base rate)", fontsize=14)
plt.tight_layout()
plt.show()

"""20 predictors tested at α=0.05 → Bonferroni-corrected threshold is 0.05/20 = 0.0025. Whatever survives *that* bar, if anything, is worth trusting; nothing between 0.0025 and 0.05 should be treated as a real finding."""

# Categorical features vs target
categorical_cols = ["Gender", "Exercise Habits", "Smoking", "Family Heart Disease", "Diabetes",
                    "High Blood Pressure", "Low HDL Cholesterol", "High LDL Cholesterol",
                    "Alcohol Consumption", "Stress Level", "Sugar Consumption"]

fig, axes = plt.subplots(4, 3, figsize=(16, 16))
for ax, col in zip(axes.flatten(), categorical_cols):
    sns.countplot(data=df, x=col, hue="Heart Disease Status", ax=ax, palette="Set2")
    ax.set_title(f"{col} vs Heart Disease Status")
    ax.tick_params(axis='x', rotation=30)
axes.flatten()[-1].axis("off")
plt.tight_layout()
plt.show()

"""**help choose which one better"""

import matplotlib.patches as mpatches

categorical_cols = ["Gender", "Exercise Habits", "Smoking", "Family Heart Disease", "Diabetes",
                    "High Blood Pressure", "Low HDL Cholesterol", "High LDL Cholesterol",
                    "Alcohol Consumption", "Stress Level", "Sugar Consumption"]

fig, axes = plt.subplots(4, 3, figsize=(16, 16))

for ax, col in zip(axes.flatten(), categorical_cols):

    temp = df.groupby([col, "Heart Disease Status"]).size().reset_index(name="Count")
    temp["Percentage"] = temp.groupby(col)["Count"].transform(lambda x: x / x.sum() * 100)

    sns.barplot(
        data=temp,
        x=col,
        y="Percentage",
        hue="Heart Disease Status",
        ax=ax,
        palette="Set2"
    )

    # Overall 20% base rate line
    ax.axhline(
        y=20,
        color="red",
        linestyle="--",
        linewidth=1
    )

    ax.set_title(f"{col}")
    ax.set_ylabel("% Heart Disease = Yes")

    # Set y-axis scale
    ax.set_ylim(0, 25)
    ax.set_yticks([0, 5, 10, 15, 20, 25])

    ax.tick_params(axis='x', rotation=30)

    # Remove individual legends
    ax.get_legend().remove()

# Turn off empty subplot
axes.flatten()[-1].axis("off")

# Create common legend
yes_patch = mpatches.Patch(
    color=sns.color_palette("Set2")[1],
    label="Heart Disease: Yes"
)

no_patch = mpatches.Patch(
    color=sns.color_palette("Set2")[0],
    label="Heart Disease: No"
)

base_patch = mpatches.Patch(
    color="red",
    label="Overall 20% base rate"
)

fig.legend(
    handles=[yes_patch, no_patch, base_patch],
    loc="upper right",
    bbox_to_anchor=(0.98, 1.04),
    title="Legend"
)

plt.suptitle(
    "Heart Disease Rate by Category (dashed line = overall 20% base rate)",
    y=1.02,
    fontsize=14
)

plt.tight_layout()
plt.show()

"""It is to show the percentage of patients with and without heart disease across different categorical predictors. The red dashed line indicates the overall heart disease of 20%, allowing comparison between individual categories and the dataset baseline. Avove 20% means the category has higher heart disease rate than average

## 8. Handling Missing Values
"""

# Before
missing_before = df.isnull().sum()

remaining_cat_cols = [c for c in categorical_cols if c != alcohol_col]

# Alcohol Consumption
df[alcohol_col] = df[alcohol_col].fillna("Unknown")

# Numeric: median
num_imputer = SimpleImputer(strategy="median")
df[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])

# Remaining: mode
cat_imputer = SimpleImputer(strategy="most_frequent")
df[remaining_cat_cols] = cat_imputer.fit_transform(df[remaining_cat_cols])

assert df.isnull().sum().sum() == 0

# After
treatment_map = (
    [(alcohol_col, "Retained as new category", "Unknown")] +
    list(zip(numeric_cols, ["Median imputation"] * len(numeric_cols), num_imputer.statistics_)) +
    list(zip(remaining_cat_cols, ["Mode imputation"] * len(remaining_cat_cols), cat_imputer.statistics_))
)

missing_treatment_summary = pd.DataFrame([
    {
        "Attribute": col,
        "Missing Count": int(missing_before[col]),
        "Treatment": treatment,
        "Imputation Value": round(value, 4) if isinstance(value, (int, float)) else value
    }
    for col, treatment, value in treatment_map
]).sort_values("Missing Count", ascending=False).reset_index(drop=True)

missing_treatment_summary

"""## 8. Encoding
Ordinal columns (Low/Medium/High, plus Alcohol's new "None" category) get an ordinal integer mapping so the order is preserved. Yes/No and Gender columns get simple binary encoding — one-hot would just add redundant columns for something that's already binary.
"""

ordinal_maps = {
    "Exercise Habits": {"Low": 0, "Medium": 1, "High": 2},
    "Stress Level": {"Low": 0, "Medium": 1, "High": 2},
    "Sugar Consumption": {"Low": 0, "Medium": 1, "High": 2},
    "Alcohol Consumption": {"Unknown": 0, "Low": 1, "Medium": 2, "High": 3},
}
for col, mapping in ordinal_maps.items():
    df[col] = df[col].map(mapping)

binary_cols = [c for c in categorical_cols if c not in ordinal_maps]
for col in binary_cols:
    le_col = LabelEncoder()
    df[col] = le_col.fit_transform(df[col])
    print(col, "->", dict(zip(le_col.classes_, le_col.transform(le_col.classes_))))

le_target = LabelEncoder()
df["target"] = le_target.fit_transform(df[target_col])


print("target mapping:", dict(zip(le_target.classes_, le_target.transform(le_target.classes_))))

feature_cols = [c for c in df.columns if c not in [target_col, "target"]]
X = df[feature_cols]
y = df["target"]
assert X.isnull().sum().sum() == 0
print("Feature matrix shape:", X.shape)

"""## 9. Train/test split and scaling
80/20 split, stratified so both sets keep the same 4:1 class ratio. SVM is distance/margin-based, so features on wildly different scales (Cholesterol ~200 vs Sleep Hours ~7) would otherwise dominate the decision boundary — standardisation is fit on train only and applied to test, to avoid leaking test statistics into training.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Train:", X_train_scaled.shape, " Test:", X_test_scaled.shape)

"""# 10. Naive Bayes"""





"""# 11. Decision Tree

Baseline model
"""

data = pd.read_csv('heart_disease.csv')                # Store dataset in dataframe
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

X

y

"""Baseline Model"""

baseline_dt = DecisionTreeClassifier(random_state=RANDOM_STATE)
baseline_dt.fit(X_train, y_train)

y_pred_base = baseline_dt.predict(X_test)

print("=== Baseline Decision Tree ===")
print("Accuracy :", round(accuracy_score(y_test, y_pred_base), 4))
print("Precision:", round(precision_score(y_test, y_pred_base), 4))
print("Recall   :", round(recall_score(y_test, y_pred_base), 4))
print("F1-score :", round(f1_score(y_test, y_pred_base), 4))

print("\nBaseline Classification Report")
print(classification_report(y_test, y_pred_base))

"""Hyperparameter Tuning"""

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE


pipeline_smote = Pipeline([
    ("smote", SMOTE(random_state=RANDOM_STATE)),
    ("classifier", DecisionTreeClassifier(
        random_state=RANDOM_STATE
    ))
])


param_grid_smote = {

    "classifier__criterion": [
        "gini",
        "entropy"
    ],

    "classifier__max_depth": [
        3,
        5,
        7,
        10,
        None
    ],

    "classifier__min_samples_split": [
        2,
        5,
        10
    ],

    "classifier__min_samples_leaf": [
        1,
        2,
        4
    ]
}


cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)


grid_smote = GridSearchCV(
    estimator=pipeline_smote,
    param_grid=param_grid_smote,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)


# Train with SMOTE
grid_smote.fit(
    X_train,
    y_train
)


best_smote_dt = grid_smote.best_estimator_


print(
    "Best Parameters:",
    grid_smote.best_params_
)

print(
    "Best CV F1:",
    round(grid_smote.best_score_,4)
)

"""Evaluation"""

y_pred_smote = best_smote_dt.predict(X_test)

y_proba_smote = best_smote_dt.predict_proba(X_test)[:,1]


print("=== SMOTE Decision Tree ===")

print(
    "Accuracy:",
    round(accuracy_score(y_test,y_pred_smote),4)
)

print(
    "Precision:",
    round(precision_score(y_test,y_pred_smote),4)
)

print(
    "Recall:",
    round(recall_score(y_test,y_pred_smote),4)
)

print(
    "F1-score:",
    round(f1_score(y_test,y_pred_smote),4)
)

print(
    "ROC-AUC:",
    round(roc_auc_score(y_test,y_proba_smote),4)
)


print(
    classification_report(
        y_test,
        y_pred_smote
    )
)

comparison = pd.DataFrame({
    "Model": [
        "Baseline Decision Tree",
        "Tuned Decision Tree",
        "SMOTE Decision Tree"
    ],

    "Accuracy": [
        accuracy_score(y_test, y_pred_base),
        accuracy_score(y_test, y_pred_tuned),
        accuracy_score(y_test, y_pred_smote)
    ],

    "Precision": [
        precision_score(y_test, y_pred_base),
        precision_score(y_test, y_pred_tuned),
        precision_score(y_test, y_pred_smote)
    ],

    "Recall": [
        recall_score(y_test, y_pred_base),
        recall_score(y_test, y_pred_tuned),
        recall_score(y_test, y_pred_smote)
    ],

    "F1-score": [
        f1_score(y_test, y_pred_base),
        f1_score(y_test, y_pred_tuned),
        f1_score(y_test, y_pred_smote)
    ]
})

comparison.round(4)

# Confusion matrices side-by-side
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred_base), display_labels=["No", "Yes"]).plot(ax=axes[0], cmap="Blues", colorbar=False)
axes[0].set_title("Baseline Decision Tree")

ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred_tuned), display_labels=["No", "Yes"]).plot(ax=axes[1], cmap="Blues", colorbar=False)
axes[1].set_title("Tuned Decision Tree")

plt.tight_layout()
plt.show()

fpr, tpr, thresholds = roc_curve(
    y_test,
    y_proba_tuned
)

auc_score = roc_auc_score(
    y_test,
    y_proba_tuned
)

plt.figure(figsize=(6,5))

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Tuned Decision Tree")
plt.legend()
plt.show()

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba_tuned)

plt.plot(fpr, tpr, label=f"Tuned Decision Tree (AUC = {roc_auc_score(y_test, y_proba_tuned):.3f})")
plt.plot([0, 1], [0, 1], linestyle="--", color="red", label="Random guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve — Tuned Decision Tree")

plt.legend()
plt.show()

# 5-fold cross-validation score (robustness check)
cv_scores = cross_val_score(y_pred_tuned, X_train, y_train, cv=cv, scoring="f1")
print("Cross-validation F1 scores:", np.round(cv_scores, 4))
print("Mean CV F1-score:", round(cv_scores.mean(), 4), " (+/-", round(cv_scores.std(), 4), ")")

# Feature importance
importances = pd.Series(y_pred_tuned.feature_importances_, index=X.columns).sort_values(ascending=False)

plt.figure(figsize=(8, 8))
sns.barplot(x=importances.values, y=importances.index, hue=importances.index, palette="viridis", legend=False)
plt.title("Feature Importance — Tuned Decision Tree")
plt.xlabel("Importance")
plt.show()

importances

# Visualise the tree (limited depth for readability)
plt.figure(figsize=(20, 10))
plot_tree(tuned_dt, max_depth=3, feature_names=X.columns, class_names=["No", "Yes"],
          filled=True, rounded=True, fontsize=9)
plt.title("Tuned Decision Tree (first 3 levels shown)")
plt.show()

"""# **Save Model**"""

# joblib.dump(y_pred_tuned, "heart_disease_decision_tree.pkl")
# joblib.dump(list(X.columns), "model_features.pkl")
# print("Model and feature list saved.")

"""# 12. Random Forest

## 13.SVM
Untuned Radial Basis Function (RBF) kernel first — this is the "before tuning" reference point everything else gets compared against.

**Baseline**
"""

# svm_baseline = SVC(kernel="rbf", C=1.0, gamma="scale", probability=True, random_state=RANDOM_STATE)
# svm_baseline.fit(X_train_scaled, y_train)

# y_pred_base = svm_baseline.predict(X_test_scaled)
# print("Baseline SVM — Test accuracy:", round(accuracy_score(y_test, y_pred_base), 4))
# print(classification_report(y_test, y_pred_base, target_names=le_target.classes_))

"""**Hyperparameter tuning**

`GridSearchCV` with 5-fold stratified CV over `kernel`, `C`, and `gamma`. Optimising for **F1**, not accuracy — with an 80/20 class split, accuracy rewards a model for ignoring the minority (disease-positive) class entirely, which is the opposite of what matters clinically.

The grid below (linear + rbf, 4 combinations x 5 folds = 20 fits) is kept small enough to actually run in a few minutes and is what produced the results shown next. `SVC` doesn't parallelise its own fits, so widening this — adding `poly`, more `C`/`gamma` values — is worth doing if you have the runtime budget (expect 15-20+ minutes for a full ~30-combination grid on this dataset size), but it won't change the substantive conclusion below.
"""

# # ==========================
# # 1. Linear SVM baseline
# # ==========================

# svm_linear = SVC(
#     kernel="linear",
#     C=1.0,
#     class_weight="balanced",
#     probability=True,
#     random_state=RANDOM_STATE
# )

# svm_linear.fit(X_train_scaled, y_train)

# y_pred_linear = svm_linear.predict(X_test_scaled)

# print("Linear SVM")
# print(classification_report(y_test, y_pred_linear))


# # ==========================
# # 2. RBF SVM baseline
# # ==========================

# svm_rbf = SVC(
#     kernel="rbf",
#     C=1.0,
#     gamma="scale",
#     class_weight="balanced",
#     probability=True,
#     random_state=RANDOM_STATE
# )

# svm_rbf.fit(X_train_scaled, y_train)

# y_pred_rbf = svm_rbf.predict(X_test_scaled)

# print("RBF SVM")
# print(classification_report(y_test, y_pred_rbf))


# # ==========================
# # 3. Tune RBF SVM
# # ==========================

# param_grid = {
#     "C": [0.1, 1, 10, 100],
#     "gamma": ["scale", 0.01, 0.1, 1]
# }


# cv = StratifiedKFold(
#     n_splits=5,
#     shuffle=True,
#     random_state=RANDOM_STATE
# )


# grid_search = GridSearchCV(
#     estimator=SVC(
#         kernel="rbf",
#         class_weight="balanced",
#         probability=True,
#         random_state=RANDOM_STATE
#     ),
#     param_grid=param_grid,
#     scoring="f1",
#     cv=cv,
#     n_jobs=1
# )


# grid_search.fit(X_train_scaled, y_train)


# print("Best parameters:", grid_search.best_params_)
# print("Best CV F1:", round(grid_search.best_score_,4))


# best_svm = grid_search.best_estimator_


# # ==========================
# # 4. Final evaluation
# # ==========================

# y_pred_best = best_svm.predict(X_test_scaled)

# print("Tuned RBF SVM")
# print(classification_report(y_test, y_pred_best))

# param_grid = [
#     {"kernel": ["linear"], "C": [1, 10]},
#     {"kernel": ["rbf"], "C": [1, 10], "gamma": ["scale", 0.1]},
# ]
# cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
# grid_search = GridSearchCV(
#     estimator=SVC(class_weight="balanced",probability=True, random_state=RANDOM_STATE),
#     param_grid=param_grid, scoring="f1", cv=cv, n_jobs=1, verbose=0,
# )
# grid_search.fit(X_train_scaled, y_train)
# print("Best parameters:", grid_search.best_params_)
# print("Best CV F1-score:", round(grid_search.best_score_, 4))
# best_svm = grid_search.best_estimator_

"""**Evaluation**"""

# y_pred = best_svm.predict(X_test_scaled)
# y_proba = best_svm.predict_proba(X_test_scaled)[:, 1]

# metrics = {
#     "Accuracy":  accuracy_score(y_test, y_pred),
#     "Precision": precision_score(y_test, y_pred, zero_division=0),
#     "Recall":    recall_score(y_test, y_pred, zero_division=0),
#     "F1-score":  f1_score(y_test, y_pred, zero_division=0),
#     "ROC-AUC":   roc_auc_score(y_test, y_proba),
# }
# svm_results = pd.DataFrame(metrics, index=["SVM (tuned)"]).round(4)
# svm_results

# cm = confusion_matrix(y_test, y_pred)
# disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le_target.classes_)
# disp.plot(cmap="Blues", values_format="d")
# plt.title("SVM (tuned) — Confusion Matrix")
# plt.show()

# fpr, tpr, _ = roc_curve(y_test, y_proba)
# plt.plot(fpr, tpr, label=f"SVM (AUC = {roc_auc_score(y_test, y_proba):.3f})")
# plt.plot([0, 1], [0, 1], linestyle="--", color="grey", label="Random guess")
# plt.xlabel("False Positive Rate")
# plt.ylabel("True Positive Rate")
# plt.title("ROC Curve — SVM")
# plt.legend()
# plt.show()

"""## 13. Feature importance
SVM has no built-in feature importance, so permutation importance instead: shuffle one feature at a time, measure how much F1 drops. A bigger drop means the model was relying on that feature more.
"""

# perm_result = permutation_importance(
#     best_svm, X_test_scaled, y_test, scoring="f1", n_repeats=10,
#     random_state=RANDOM_STATE, n_jobs=-1
# )

# perm_importance_df = pd.DataFrame({
#     "feature": X.columns,
#     "importance_mean": perm_result.importances_mean,
#     "importance_std": perm_result.importances_std,
# }).sort_values("importance_mean", ascending=False)

# plt.figure(figsize=(8, 6))
# sns.barplot(data=perm_importance_df.head(15), x="importance_mean", y="feature", color="steelblue")
# plt.title("Top 15 Features by Permutation Importance — SVM")
# plt.xlabel("Mean F1-score decrease")
# plt.tight_layout()
# plt.show()

# perm_importance_df

"""## 14. Save artefacts"""

# joblib.dump(best_svm, "svm_model.pkl")
# joblib.dump(scaler, "svm_scaler.pkl")
# joblib.dump(list(X.columns), "svm_feature_columns.pkl")
# joblib.dump(le_target, "svm_target_encoder.pkl")
# print("Saved model artefacts.")

"""## References
- Little, R. J. A., & Rubin, D. B. (2019). *Statistical Analysis with Missing Data* (3rd ed.). Wiley.
- Cortes, C., & Vapnik, V. (1995). Support-vector networks. *Machine Learning, 20*(3), 273–297.
- Mohan, S., Thirumalai, C., & Srivastava, G. (2019). Effective heart disease prediction using hybrid machine learning techniques. *IEEE Access, 7*, 81542–81554.
- Ordekci, O. (2024). *Heart disease data for health research* [Data set]. Kaggle.
"""